### ISSUE TITLE
Symlink edge case

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason-js#47]
When a package has a symlink in the source files, it looks like `mason-js` dies on this. To replicate:

 - install a package
 - link it
 - attempt to link a second time 💥 

Example:

```
~/projects/mason-js[master]$ ./bin/mason-js install clang++=5.0.1 --type=compiled
info check checked for clang++ (not found locally)
info tarball done parsing tarball for clang++
info Finished downloading packages 
info Completed 
~/projects/mason-js[master]$ ./bin/mason-js link clang++=5.0.1 --type=compiled
info Symlinked:  /Users/dane/projects/mason-js/mason_packages/osx-x86_64/clang++/5.0.1 to  /Users/dane/projects/mason-js/mason_packages/.link
info Completed 
~/projects/mason-js[master]$ ./bin/mason-js link clang++=5.0.1 --type=compiled
ERR! Error: EEXIST: file already exists, symlink 'asan_symbolize.py' -> '/Users/dane/projects/mason-js/mason_packages/.link/bin/asan_symbolize' 
```

If I remove all the symlinks inside `mason_packages/osx-x86_64/clang++/5.0.1/bin/` then the problem goes away.

**Comment by millzpaugh** [comment]
There are empty symlinked directories in mason packages that error when attempting to overwrite them via the `mason-js link` command. 

PRs #48 and #52 attempted to address linking symlinks, but unfortunately, these fixes have just generated different symlink errors in the node-cpp-skel proposed mason-js port. 

The latest error in the node-cpp-skel travis build is: 
```mkdir -p ./mason_packages; ./node_modules/.bin/mason-js link
info Symlinked:  /home/travis/build/mapbox/node-cpp-skel/mason_packages/headers/protozero/1.6.1 to  /home/travis/build/mapbox/node-cpp-skel/mason_packages/.link
ERR! Error: EEXIST: file already exists, symlink 'asan_symbolize.py' -> '/home/travis/build/mapbox/node-cpp-skel/mason_packages/.link/bin/asan_symbolize' 
make[1]: *** [mason_packages/.link] Error 1```

This issue needs to be resolved before incorporating mason-js as a project dependency.

**Comment by millzpaugh** [comment]
**The Problem!** 

Appending [the `lsync` property to `filterFunc` in the `paths`](https://github.com/mapbox/mason-js/commit/36b0d6c7845ff4d9ca4e3dde447f0dfd584f365c#diff-576e36b8d51a5cec7021f95d4f9ab5b1R34) forLoop caused the stats object to return the _directory_ path instead of the full destination path. Therefore, the symlink checks were consistently failing because they were checking the directory and not the file path itself.  The full destination path doesn't become available until we are inside the `filterFunc` function. This has been resolved in the latest release - `v.0.1.4`.
